import type { Metadata } from "next";
import NavBar from "./Components/NavBar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-main h-full`}>
        <NavBar />
        <div className="h-screen flex flex-col">{children}</div>
      </body>
    </html>
  );
}
